### ISSUE TITLE
Create README File

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/Club-Panda#4]
This is a rather old project of mine. It would be nice if someone could create a README file outlining how to contribute to the project and run it.

**Comment by SamrudaPobbathi** [comment]
I am interested in creating the README, can you give me more resources to do so? Or can you give me more pointers?

**Comment by jrtechs** [comment]
@mobeenabdullah Just finished this project with pull request #5. @SamrudaPobbathi If you would like to add more to the read me that would be great. To add to the README all you need to do is write the file in markdown. If you do feel like adding anything @SamrudaPobbathi , write about running this project with PHP, mysql, and apache.
